### ISSUE TITLE
关于React-Native拆包中遇到的js依赖问题

### ISSUE THREAD

**Issue by njafei** [atrl/reactNativePackageDemo#3]
你好，我之前看了你们音乐团队技术博客你分享的React-Native的拆包方案，实践了下， 目前js的拆包和Native端的代码都没有问题，但是发现最终合并的包在执行的时候会报错，我比较了下，发现是单独打的业务包，有些依赖的函数不对，对比如下：

正确的包：
__d(function(e,t,r,n){Object.defineProperty(n,"__esModule",{value:!0});var l=t(12),o=babelHelpers.interopRequireDefault(l),a=t(39),i=function(e){function t(){return babelHelpers.classCallCheck(this,t),babelHelpers.possibleConstructorReturn(this,(t.__proto__||Object.getPrototypeOf(t)).apply(this,arguments))}return babelHelpers.inherits(t,e),babelHelpers.createClass(t,[{key:"render",value:function(){return o.default.createElement(a.View,{style:c.container},o.default.createElement(a.Text,{style:c.welcome},"Welcome to commonbridge1!"))}}]),t}(l.Component);n.default=i;var c=a.StyleSheet.create({container:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:"#F5FCFF"},welcome:{fontSize:20,textAlign:"center",margin:10},instructions:{textAlign:"center",color:"#333333",marginBottom:5}});a.AppRegistry.registerComponent("ReactExample",function(){return i})},0);

单独打出来的包：
__d(function(e,t,r,n){Object.defineProperty(n,"__esModule",{value:!0});var l=t(1),o=babelHelpers.interopRequireDefault(l),a=t(2),i=function(e){function t(){return babelHelpers.classCallCheck(this,t),babelHelpers.possibleConstructorReturn(this,(t.__proto__||Object.getPrototypeOf(t)).apply(this,arguments))}return babelHelpers.inherits(t,e),babelHelpers.createClass(t,[{key:"render",value:function(){return o.default.createElement(a.View,{style:c.container},o.default.createElement(a.Text,{style:c.welcome},"Welcome to commonbridge1!"))}}]),t}(l.Component);n.default=i;var c=a.StyleSheet.create({container:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:"#F5FCFF"},welcome:{fontSize:20,textAlign:"center",margin:10},instructions:{textAlign:"center",color:"#333333",marginBottom:5}});a.AppRegistry.registerComponent("ReactExample",function(){return i})},0);

里面有些函数的名称如：12、39，在单独打出来的包中就是1、2，请问你们在拆包的时候有遇到这个问题吗？是如何解决的呢？

谢谢。

**Comment by atrl** [comment]
改了打包的方法 针对基础包模块名生成一份映射  业务模块打包的时候根据这个映射找Id

**Comment by njafei** [comment]
谢谢，解决了我的问题
